[package]
name = "trezor_lib"
version = "0.1.0"
authors = ["SatoshiLabs <info@satoshilabs.com>"]
edition = "2021"
build = "build.rs"

[features]
default = ["model_tt", "use_altcoins"]
use_altcoins = ["use_zcash"]
model_tt = ["touch"]
model_t1 = ["buttons"]
model_tr = ["buttons"]
micropython = []
protobuf = ["micropython"]
use_zcash = ["micropython", "f4jumble", "blake2b_simd"]
ui = []
ui_debug = []
buttons = []
touch = []
clippy = []
test = ["cc", "glob", "micropython", "protobuf", "use_zcash", "ui", "ui_debug"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
split-debuginfo = "unpacked"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

[profile.test]
split-debuginfo = "unpacked"

# Runtime dependencies

[dependencies.cty]
version = "0.2.2"

[dependencies.heapless]
version = "0.7.3"
default_features = false

[dependencies.cstr_core]
version = "0.2.4"
default_features = false

[dependencies.f4jumble]
version = "0.1.0"
default-features = false
optional = true

[dependencies.blake2b_simd]
# this is a dependency of f4jumble crate
# we recall it here to enable its `uninline_portable` feature
version = "1"
default_features = false
features = ["uninline_portable"]
optional = true

# Build dependencies

[build-dependencies.bindgen]
version = "0.60.1"
default_features = false
features = ["runtime"]

# Build dependencies used for linking the test binary

[build-dependencies.cc]
optional = true
version = "1.0.69"

[build-dependencies.glob]
optional = true
version = "0.3.0"
